name: jci_remit_mobile
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_hooks: ^0.15.0
  hooks_riverpod: ^0.12.1
  dio: ^3.0.10
  pretty_dio_logger: ^1.1.1
  google_fonts: ^1.1.1
  equatable: ^1.2.5
  flushbar: ^1.10.4
  flutter_icons: ^1.1.0
  shared_preferences: ^0.5.8
  connectivity: ^2.0.1
  intl_phone_number_input: ^0.5.2+2
  liquid_pull_to_refresh: ^2.0.0
  date_field: ^2.0.1
  flow_builder: ^0.0.2
  page_transition: ^2.0.2
  modal_bottom_sheet: ^2.0.0

   # Utils
  logger: ^1.0.0
  date_format: ^2.0.2
  flutter_screenutil: ^3.2.0


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/images/svg/
    - assets/icons/
    - assets/loittie/

